################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/threadx/src/tx_block_allocate.c \
../src/threadx/src/tx_block_pool_cleanup.c \
../src/threadx/src/tx_block_pool_create.c \
../src/threadx/src/tx_block_pool_delete.c \
../src/threadx/src/tx_block_pool_info_get.c \
../src/threadx/src/tx_block_pool_initialize.c \
../src/threadx/src/tx_block_pool_performance_info_get.c \
../src/threadx/src/tx_block_pool_performance_system_info_get.c \
../src/threadx/src/tx_block_pool_prioritize.c \
../src/threadx/src/tx_block_release.c \
../src/threadx/src/tx_byte_allocate.c \
../src/threadx/src/tx_byte_pool_cleanup.c \
../src/threadx/src/tx_byte_pool_create.c \
../src/threadx/src/tx_byte_pool_delete.c \
../src/threadx/src/tx_byte_pool_info_get.c \
../src/threadx/src/tx_byte_pool_initialize.c \
../src/threadx/src/tx_byte_pool_performance_info_get.c \
../src/threadx/src/tx_byte_pool_performance_system_info_get.c \
../src/threadx/src/tx_byte_pool_prioritize.c \
../src/threadx/src/tx_byte_pool_search.c \
../src/threadx/src/tx_byte_release.c \
../src/threadx/src/tx_event_flags_cleanup.c \
../src/threadx/src/tx_event_flags_create.c \
../src/threadx/src/tx_event_flags_delete.c \
../src/threadx/src/tx_event_flags_get.c \
../src/threadx/src/tx_event_flags_info_get.c \
../src/threadx/src/tx_event_flags_initialize.c \
../src/threadx/src/tx_event_flags_performance_info_get.c \
../src/threadx/src/tx_event_flags_performance_system_info_get.c \
../src/threadx/src/tx_event_flags_set.c \
../src/threadx/src/tx_event_flags_set_notify.c \
../src/threadx/src/tx_initialize_high_level.c \
../src/threadx/src/tx_initialize_kernel_enter.c \
../src/threadx/src/tx_initialize_kernel_setup.c \
../src/threadx/src/tx_misra.c \
../src/threadx/src/tx_mutex_cleanup.c \
../src/threadx/src/tx_mutex_create.c \
../src/threadx/src/tx_mutex_delete.c \
../src/threadx/src/tx_mutex_get.c \
../src/threadx/src/tx_mutex_info_get.c \
../src/threadx/src/tx_mutex_initialize.c \
../src/threadx/src/tx_mutex_performance_info_get.c \
../src/threadx/src/tx_mutex_performance_system_info_get.c \
../src/threadx/src/tx_mutex_prioritize.c \
../src/threadx/src/tx_mutex_priority_change.c \
../src/threadx/src/tx_mutex_put.c \
../src/threadx/src/tx_queue_cleanup.c \
../src/threadx/src/tx_queue_create.c \
../src/threadx/src/tx_queue_delete.c \
../src/threadx/src/tx_queue_flush.c \
../src/threadx/src/tx_queue_front_send.c \
../src/threadx/src/tx_queue_info_get.c \
../src/threadx/src/tx_queue_initialize.c \
../src/threadx/src/tx_queue_performance_info_get.c \
../src/threadx/src/tx_queue_performance_system_info_get.c \
../src/threadx/src/tx_queue_prioritize.c \
../src/threadx/src/tx_queue_receive.c \
../src/threadx/src/tx_queue_send.c \
../src/threadx/src/tx_queue_send_notify.c \
../src/threadx/src/tx_semaphore_ceiling_put.c \
../src/threadx/src/tx_semaphore_cleanup.c \
../src/threadx/src/tx_semaphore_create.c \
../src/threadx/src/tx_semaphore_delete.c \
../src/threadx/src/tx_semaphore_get.c \
../src/threadx/src/tx_semaphore_info_get.c \
../src/threadx/src/tx_semaphore_initialize.c \
../src/threadx/src/tx_semaphore_performance_info_get.c \
../src/threadx/src/tx_semaphore_performance_system_info_get.c \
../src/threadx/src/tx_semaphore_prioritize.c \
../src/threadx/src/tx_semaphore_put.c \
../src/threadx/src/tx_semaphore_put_notify.c \
../src/threadx/src/tx_thread_create.c \
../src/threadx/src/tx_thread_delete.c \
../src/threadx/src/tx_thread_entry_exit_notify.c \
../src/threadx/src/tx_thread_identify.c \
../src/threadx/src/tx_thread_info_get.c \
../src/threadx/src/tx_thread_initialize.c \
../src/threadx/src/tx_thread_performance_info_get.c \
../src/threadx/src/tx_thread_performance_system_info_get.c \
../src/threadx/src/tx_thread_preemption_change.c \
../src/threadx/src/tx_thread_priority_change.c \
../src/threadx/src/tx_thread_relinquish.c \
../src/threadx/src/tx_thread_reset.c \
../src/threadx/src/tx_thread_resume.c \
../src/threadx/src/tx_thread_shell_entry.c \
../src/threadx/src/tx_thread_sleep.c \
../src/threadx/src/tx_thread_stack_analyze.c \
../src/threadx/src/tx_thread_stack_error_handler.c \
../src/threadx/src/tx_thread_stack_error_notify.c \
../src/threadx/src/tx_thread_suspend.c \
../src/threadx/src/tx_thread_system_preempt_check.c \
../src/threadx/src/tx_thread_system_resume.c \
../src/threadx/src/tx_thread_system_suspend.c \
../src/threadx/src/tx_thread_terminate.c \
../src/threadx/src/tx_thread_time_slice.c \
../src/threadx/src/tx_thread_time_slice_change.c \
../src/threadx/src/tx_thread_timeout.c \
../src/threadx/src/tx_thread_wait_abort.c \
../src/threadx/src/tx_time_get.c \
../src/threadx/src/tx_time_set.c \
../src/threadx/src/tx_timer_activate.c \
../src/threadx/src/tx_timer_change.c \
../src/threadx/src/tx_timer_create.c \
../src/threadx/src/tx_timer_deactivate.c \
../src/threadx/src/tx_timer_delete.c \
../src/threadx/src/tx_timer_expiration_process.c \
../src/threadx/src/tx_timer_info_get.c \
../src/threadx/src/tx_timer_initialize.c \
../src/threadx/src/tx_timer_performance_info_get.c \
../src/threadx/src/tx_timer_performance_system_info_get.c \
../src/threadx/src/tx_timer_system_activate.c \
../src/threadx/src/tx_timer_system_deactivate.c \
../src/threadx/src/tx_timer_thread_entry.c \
../src/threadx/src/tx_trace_buffer_full_notify.c \
../src/threadx/src/tx_trace_disable.c \
../src/threadx/src/tx_trace_enable.c \
../src/threadx/src/tx_trace_event_filter.c \
../src/threadx/src/tx_trace_event_unfilter.c \
../src/threadx/src/tx_trace_initialize.c \
../src/threadx/src/tx_trace_interrupt_control.c \
../src/threadx/src/tx_trace_isr_enter_insert.c \
../src/threadx/src/tx_trace_isr_exit_insert.c \
../src/threadx/src/tx_trace_object_register.c \
../src/threadx/src/tx_trace_object_unregister.c \
../src/threadx/src/tx_trace_user_event_insert.c \
../src/threadx/src/txe_block_allocate.c \
../src/threadx/src/txe_block_pool_create.c \
../src/threadx/src/txe_block_pool_delete.c \
../src/threadx/src/txe_block_pool_info_get.c \
../src/threadx/src/txe_block_pool_prioritize.c \
../src/threadx/src/txe_block_release.c \
../src/threadx/src/txe_byte_allocate.c \
../src/threadx/src/txe_byte_pool_create.c \
../src/threadx/src/txe_byte_pool_delete.c \
../src/threadx/src/txe_byte_pool_info_get.c \
../src/threadx/src/txe_byte_pool_prioritize.c \
../src/threadx/src/txe_byte_release.c \
../src/threadx/src/txe_event_flags_create.c \
../src/threadx/src/txe_event_flags_delete.c \
../src/threadx/src/txe_event_flags_get.c \
../src/threadx/src/txe_event_flags_info_get.c \
../src/threadx/src/txe_event_flags_set.c \
../src/threadx/src/txe_event_flags_set_notify.c \
../src/threadx/src/txe_mutex_create.c \
../src/threadx/src/txe_mutex_delete.c \
../src/threadx/src/txe_mutex_get.c \
../src/threadx/src/txe_mutex_info_get.c \
../src/threadx/src/txe_mutex_prioritize.c \
../src/threadx/src/txe_mutex_put.c \
../src/threadx/src/txe_queue_create.c \
../src/threadx/src/txe_queue_delete.c \
../src/threadx/src/txe_queue_flush.c \
../src/threadx/src/txe_queue_front_send.c \
../src/threadx/src/txe_queue_info_get.c \
../src/threadx/src/txe_queue_prioritize.c \
../src/threadx/src/txe_queue_receive.c \
../src/threadx/src/txe_queue_send.c \
../src/threadx/src/txe_queue_send_notify.c \
../src/threadx/src/txe_semaphore_ceiling_put.c \
../src/threadx/src/txe_semaphore_create.c \
../src/threadx/src/txe_semaphore_delete.c \
../src/threadx/src/txe_semaphore_get.c \
../src/threadx/src/txe_semaphore_info_get.c \
../src/threadx/src/txe_semaphore_prioritize.c \
../src/threadx/src/txe_semaphore_put.c \
../src/threadx/src/txe_semaphore_put_notify.c \
../src/threadx/src/txe_thread_create.c \
../src/threadx/src/txe_thread_delete.c \
../src/threadx/src/txe_thread_entry_exit_notify.c \
../src/threadx/src/txe_thread_info_get.c \
../src/threadx/src/txe_thread_preemption_change.c \
../src/threadx/src/txe_thread_priority_change.c \
../src/threadx/src/txe_thread_relinquish.c \
../src/threadx/src/txe_thread_reset.c \
../src/threadx/src/txe_thread_resume.c \
../src/threadx/src/txe_thread_suspend.c \
../src/threadx/src/txe_thread_terminate.c \
../src/threadx/src/txe_thread_time_slice_change.c \
../src/threadx/src/txe_thread_wait_abort.c \
../src/threadx/src/txe_timer_activate.c \
../src/threadx/src/txe_timer_change.c \
../src/threadx/src/txe_timer_create.c \
../src/threadx/src/txe_timer_deactivate.c \
../src/threadx/src/txe_timer_delete.c \
../src/threadx/src/txe_timer_info_get.c 

C_DEPS += \
./src/threadx/src/tx_block_allocate.d \
./src/threadx/src/tx_block_pool_cleanup.d \
./src/threadx/src/tx_block_pool_create.d \
./src/threadx/src/tx_block_pool_delete.d \
./src/threadx/src/tx_block_pool_info_get.d \
./src/threadx/src/tx_block_pool_initialize.d \
./src/threadx/src/tx_block_pool_performance_info_get.d \
./src/threadx/src/tx_block_pool_performance_system_info_get.d \
./src/threadx/src/tx_block_pool_prioritize.d \
./src/threadx/src/tx_block_release.d \
./src/threadx/src/tx_byte_allocate.d \
./src/threadx/src/tx_byte_pool_cleanup.d \
./src/threadx/src/tx_byte_pool_create.d \
./src/threadx/src/tx_byte_pool_delete.d \
./src/threadx/src/tx_byte_pool_info_get.d \
./src/threadx/src/tx_byte_pool_initialize.d \
./src/threadx/src/tx_byte_pool_performance_info_get.d \
./src/threadx/src/tx_byte_pool_performance_system_info_get.d \
./src/threadx/src/tx_byte_pool_prioritize.d \
./src/threadx/src/tx_byte_pool_search.d \
./src/threadx/src/tx_byte_release.d \
./src/threadx/src/tx_event_flags_cleanup.d \
./src/threadx/src/tx_event_flags_create.d \
./src/threadx/src/tx_event_flags_delete.d \
./src/threadx/src/tx_event_flags_get.d \
./src/threadx/src/tx_event_flags_info_get.d \
./src/threadx/src/tx_event_flags_initialize.d \
./src/threadx/src/tx_event_flags_performance_info_get.d \
./src/threadx/src/tx_event_flags_performance_system_info_get.d \
./src/threadx/src/tx_event_flags_set.d \
./src/threadx/src/tx_event_flags_set_notify.d \
./src/threadx/src/tx_initialize_high_level.d \
./src/threadx/src/tx_initialize_kernel_enter.d \
./src/threadx/src/tx_initialize_kernel_setup.d \
./src/threadx/src/tx_misra.d \
./src/threadx/src/tx_mutex_cleanup.d \
./src/threadx/src/tx_mutex_create.d \
./src/threadx/src/tx_mutex_delete.d \
./src/threadx/src/tx_mutex_get.d \
./src/threadx/src/tx_mutex_info_get.d \
./src/threadx/src/tx_mutex_initialize.d \
./src/threadx/src/tx_mutex_performance_info_get.d \
./src/threadx/src/tx_mutex_performance_system_info_get.d \
./src/threadx/src/tx_mutex_prioritize.d \
./src/threadx/src/tx_mutex_priority_change.d \
./src/threadx/src/tx_mutex_put.d \
./src/threadx/src/tx_queue_cleanup.d \
./src/threadx/src/tx_queue_create.d \
./src/threadx/src/tx_queue_delete.d \
./src/threadx/src/tx_queue_flush.d \
./src/threadx/src/tx_queue_front_send.d \
./src/threadx/src/tx_queue_info_get.d \
./src/threadx/src/tx_queue_initialize.d \
./src/threadx/src/tx_queue_performance_info_get.d \
./src/threadx/src/tx_queue_performance_system_info_get.d \
./src/threadx/src/tx_queue_prioritize.d \
./src/threadx/src/tx_queue_receive.d \
./src/threadx/src/tx_queue_send.d \
./src/threadx/src/tx_queue_send_notify.d \
./src/threadx/src/tx_semaphore_ceiling_put.d \
./src/threadx/src/tx_semaphore_cleanup.d \
./src/threadx/src/tx_semaphore_create.d \
./src/threadx/src/tx_semaphore_delete.d \
./src/threadx/src/tx_semaphore_get.d \
./src/threadx/src/tx_semaphore_info_get.d \
./src/threadx/src/tx_semaphore_initialize.d \
./src/threadx/src/tx_semaphore_performance_info_get.d \
./src/threadx/src/tx_semaphore_performance_system_info_get.d \
./src/threadx/src/tx_semaphore_prioritize.d \
./src/threadx/src/tx_semaphore_put.d \
./src/threadx/src/tx_semaphore_put_notify.d \
./src/threadx/src/tx_thread_create.d \
./src/threadx/src/tx_thread_delete.d \
./src/threadx/src/tx_thread_entry_exit_notify.d \
./src/threadx/src/tx_thread_identify.d \
./src/threadx/src/tx_thread_info_get.d \
./src/threadx/src/tx_thread_initialize.d \
./src/threadx/src/tx_thread_performance_info_get.d \
./src/threadx/src/tx_thread_performance_system_info_get.d \
./src/threadx/src/tx_thread_preemption_change.d \
./src/threadx/src/tx_thread_priority_change.d \
./src/threadx/src/tx_thread_relinquish.d \
./src/threadx/src/tx_thread_reset.d \
./src/threadx/src/tx_thread_resume.d \
./src/threadx/src/tx_thread_shell_entry.d \
./src/threadx/src/tx_thread_sleep.d \
./src/threadx/src/tx_thread_stack_analyze.d \
./src/threadx/src/tx_thread_stack_error_handler.d \
./src/threadx/src/tx_thread_stack_error_notify.d \
./src/threadx/src/tx_thread_suspend.d \
./src/threadx/src/tx_thread_system_preempt_check.d \
./src/threadx/src/tx_thread_system_resume.d \
./src/threadx/src/tx_thread_system_suspend.d \
./src/threadx/src/tx_thread_terminate.d \
./src/threadx/src/tx_thread_time_slice.d \
./src/threadx/src/tx_thread_time_slice_change.d \
./src/threadx/src/tx_thread_timeout.d \
./src/threadx/src/tx_thread_wait_abort.d \
./src/threadx/src/tx_time_get.d \
./src/threadx/src/tx_time_set.d \
./src/threadx/src/tx_timer_activate.d \
./src/threadx/src/tx_timer_change.d \
./src/threadx/src/tx_timer_create.d \
./src/threadx/src/tx_timer_deactivate.d \
./src/threadx/src/tx_timer_delete.d \
./src/threadx/src/tx_timer_expiration_process.d \
./src/threadx/src/tx_timer_info_get.d \
./src/threadx/src/tx_timer_initialize.d \
./src/threadx/src/tx_timer_performance_info_get.d \
./src/threadx/src/tx_timer_performance_system_info_get.d \
./src/threadx/src/tx_timer_system_activate.d \
./src/threadx/src/tx_timer_system_deactivate.d \
./src/threadx/src/tx_timer_thread_entry.d \
./src/threadx/src/tx_trace_buffer_full_notify.d \
./src/threadx/src/tx_trace_disable.d \
./src/threadx/src/tx_trace_enable.d \
./src/threadx/src/tx_trace_event_filter.d \
./src/threadx/src/tx_trace_event_unfilter.d \
./src/threadx/src/tx_trace_initialize.d \
./src/threadx/src/tx_trace_interrupt_control.d \
./src/threadx/src/tx_trace_isr_enter_insert.d \
./src/threadx/src/tx_trace_isr_exit_insert.d \
./src/threadx/src/tx_trace_object_register.d \
./src/threadx/src/tx_trace_object_unregister.d \
./src/threadx/src/tx_trace_user_event_insert.d \
./src/threadx/src/txe_block_allocate.d \
./src/threadx/src/txe_block_pool_create.d \
./src/threadx/src/txe_block_pool_delete.d \
./src/threadx/src/txe_block_pool_info_get.d \
./src/threadx/src/txe_block_pool_prioritize.d \
./src/threadx/src/txe_block_release.d \
./src/threadx/src/txe_byte_allocate.d \
./src/threadx/src/txe_byte_pool_create.d \
./src/threadx/src/txe_byte_pool_delete.d \
./src/threadx/src/txe_byte_pool_info_get.d \
./src/threadx/src/txe_byte_pool_prioritize.d \
./src/threadx/src/txe_byte_release.d \
./src/threadx/src/txe_event_flags_create.d \
./src/threadx/src/txe_event_flags_delete.d \
./src/threadx/src/txe_event_flags_get.d \
./src/threadx/src/txe_event_flags_info_get.d \
./src/threadx/src/txe_event_flags_set.d \
./src/threadx/src/txe_event_flags_set_notify.d \
./src/threadx/src/txe_mutex_create.d \
./src/threadx/src/txe_mutex_delete.d \
./src/threadx/src/txe_mutex_get.d \
./src/threadx/src/txe_mutex_info_get.d \
./src/threadx/src/txe_mutex_prioritize.d \
./src/threadx/src/txe_mutex_put.d \
./src/threadx/src/txe_queue_create.d \
./src/threadx/src/txe_queue_delete.d \
./src/threadx/src/txe_queue_flush.d \
./src/threadx/src/txe_queue_front_send.d \
./src/threadx/src/txe_queue_info_get.d \
./src/threadx/src/txe_queue_prioritize.d \
./src/threadx/src/txe_queue_receive.d \
./src/threadx/src/txe_queue_send.d \
./src/threadx/src/txe_queue_send_notify.d \
./src/threadx/src/txe_semaphore_ceiling_put.d \
./src/threadx/src/txe_semaphore_create.d \
./src/threadx/src/txe_semaphore_delete.d \
./src/threadx/src/txe_semaphore_get.d \
./src/threadx/src/txe_semaphore_info_get.d \
./src/threadx/src/txe_semaphore_prioritize.d \
./src/threadx/src/txe_semaphore_put.d \
./src/threadx/src/txe_semaphore_put_notify.d \
./src/threadx/src/txe_thread_create.d \
./src/threadx/src/txe_thread_delete.d \
./src/threadx/src/txe_thread_entry_exit_notify.d \
./src/threadx/src/txe_thread_info_get.d \
./src/threadx/src/txe_thread_preemption_change.d \
./src/threadx/src/txe_thread_priority_change.d \
./src/threadx/src/txe_thread_relinquish.d \
./src/threadx/src/txe_thread_reset.d \
./src/threadx/src/txe_thread_resume.d \
./src/threadx/src/txe_thread_suspend.d \
./src/threadx/src/txe_thread_terminate.d \
./src/threadx/src/txe_thread_time_slice_change.d \
./src/threadx/src/txe_thread_wait_abort.d \
./src/threadx/src/txe_timer_activate.d \
./src/threadx/src/txe_timer_change.d \
./src/threadx/src/txe_timer_create.d \
./src/threadx/src/txe_timer_deactivate.d \
./src/threadx/src/txe_timer_delete.d \
./src/threadx/src/txe_timer_info_get.d 

OBJS += \
./src/threadx/src/tx_block_allocate.o \
./src/threadx/src/tx_block_pool_cleanup.o \
./src/threadx/src/tx_block_pool_create.o \
./src/threadx/src/tx_block_pool_delete.o \
./src/threadx/src/tx_block_pool_info_get.o \
./src/threadx/src/tx_block_pool_initialize.o \
./src/threadx/src/tx_block_pool_performance_info_get.o \
./src/threadx/src/tx_block_pool_performance_system_info_get.o \
./src/threadx/src/tx_block_pool_prioritize.o \
./src/threadx/src/tx_block_release.o \
./src/threadx/src/tx_byte_allocate.o \
./src/threadx/src/tx_byte_pool_cleanup.o \
./src/threadx/src/tx_byte_pool_create.o \
./src/threadx/src/tx_byte_pool_delete.o \
./src/threadx/src/tx_byte_pool_info_get.o \
./src/threadx/src/tx_byte_pool_initialize.o \
./src/threadx/src/tx_byte_pool_performance_info_get.o \
./src/threadx/src/tx_byte_pool_performance_system_info_get.o \
./src/threadx/src/tx_byte_pool_prioritize.o \
./src/threadx/src/tx_byte_pool_search.o \
./src/threadx/src/tx_byte_release.o \
./src/threadx/src/tx_event_flags_cleanup.o \
./src/threadx/src/tx_event_flags_create.o \
./src/threadx/src/tx_event_flags_delete.o \
./src/threadx/src/tx_event_flags_get.o \
./src/threadx/src/tx_event_flags_info_get.o \
./src/threadx/src/tx_event_flags_initialize.o \
./src/threadx/src/tx_event_flags_performance_info_get.o \
./src/threadx/src/tx_event_flags_performance_system_info_get.o \
./src/threadx/src/tx_event_flags_set.o \
./src/threadx/src/tx_event_flags_set_notify.o \
./src/threadx/src/tx_initialize_high_level.o \
./src/threadx/src/tx_initialize_kernel_enter.o \
./src/threadx/src/tx_initialize_kernel_setup.o \
./src/threadx/src/tx_misra.o \
./src/threadx/src/tx_mutex_cleanup.o \
./src/threadx/src/tx_mutex_create.o \
./src/threadx/src/tx_mutex_delete.o \
./src/threadx/src/tx_mutex_get.o \
./src/threadx/src/tx_mutex_info_get.o \
./src/threadx/src/tx_mutex_initialize.o \
./src/threadx/src/tx_mutex_performance_info_get.o \
./src/threadx/src/tx_mutex_performance_system_info_get.o \
./src/threadx/src/tx_mutex_prioritize.o \
./src/threadx/src/tx_mutex_priority_change.o \
./src/threadx/src/tx_mutex_put.o \
./src/threadx/src/tx_queue_cleanup.o \
./src/threadx/src/tx_queue_create.o \
./src/threadx/src/tx_queue_delete.o \
./src/threadx/src/tx_queue_flush.o \
./src/threadx/src/tx_queue_front_send.o \
./src/threadx/src/tx_queue_info_get.o \
./src/threadx/src/tx_queue_initialize.o \
./src/threadx/src/tx_queue_performance_info_get.o \
./src/threadx/src/tx_queue_performance_system_info_get.o \
./src/threadx/src/tx_queue_prioritize.o \
./src/threadx/src/tx_queue_receive.o \
./src/threadx/src/tx_queue_send.o \
./src/threadx/src/tx_queue_send_notify.o \
./src/threadx/src/tx_semaphore_ceiling_put.o \
./src/threadx/src/tx_semaphore_cleanup.o \
./src/threadx/src/tx_semaphore_create.o \
./src/threadx/src/tx_semaphore_delete.o \
./src/threadx/src/tx_semaphore_get.o \
./src/threadx/src/tx_semaphore_info_get.o \
./src/threadx/src/tx_semaphore_initialize.o \
./src/threadx/src/tx_semaphore_performance_info_get.o \
./src/threadx/src/tx_semaphore_performance_system_info_get.o \
./src/threadx/src/tx_semaphore_prioritize.o \
./src/threadx/src/tx_semaphore_put.o \
./src/threadx/src/tx_semaphore_put_notify.o \
./src/threadx/src/tx_thread_create.o \
./src/threadx/src/tx_thread_delete.o \
./src/threadx/src/tx_thread_entry_exit_notify.o \
./src/threadx/src/tx_thread_identify.o \
./src/threadx/src/tx_thread_info_get.o \
./src/threadx/src/tx_thread_initialize.o \
./src/threadx/src/tx_thread_performance_info_get.o \
./src/threadx/src/tx_thread_performance_system_info_get.o \
./src/threadx/src/tx_thread_preemption_change.o \
./src/threadx/src/tx_thread_priority_change.o \
./src/threadx/src/tx_thread_relinquish.o \
./src/threadx/src/tx_thread_reset.o \
./src/threadx/src/tx_thread_resume.o \
./src/threadx/src/tx_thread_shell_entry.o \
./src/threadx/src/tx_thread_sleep.o \
./src/threadx/src/tx_thread_stack_analyze.o \
./src/threadx/src/tx_thread_stack_error_handler.o \
./src/threadx/src/tx_thread_stack_error_notify.o \
./src/threadx/src/tx_thread_suspend.o \
./src/threadx/src/tx_thread_system_preempt_check.o \
./src/threadx/src/tx_thread_system_resume.o \
./src/threadx/src/tx_thread_system_suspend.o \
./src/threadx/src/tx_thread_terminate.o \
./src/threadx/src/tx_thread_time_slice.o \
./src/threadx/src/tx_thread_time_slice_change.o \
./src/threadx/src/tx_thread_timeout.o \
./src/threadx/src/tx_thread_wait_abort.o \
./src/threadx/src/tx_time_get.o \
./src/threadx/src/tx_time_set.o \
./src/threadx/src/tx_timer_activate.o \
./src/threadx/src/tx_timer_change.o \
./src/threadx/src/tx_timer_create.o \
./src/threadx/src/tx_timer_deactivate.o \
./src/threadx/src/tx_timer_delete.o \
./src/threadx/src/tx_timer_expiration_process.o \
./src/threadx/src/tx_timer_info_get.o \
./src/threadx/src/tx_timer_initialize.o \
./src/threadx/src/tx_timer_performance_info_get.o \
./src/threadx/src/tx_timer_performance_system_info_get.o \
./src/threadx/src/tx_timer_system_activate.o \
./src/threadx/src/tx_timer_system_deactivate.o \
./src/threadx/src/tx_timer_thread_entry.o \
./src/threadx/src/tx_trace_buffer_full_notify.o \
./src/threadx/src/tx_trace_disable.o \
./src/threadx/src/tx_trace_enable.o \
./src/threadx/src/tx_trace_event_filter.o \
./src/threadx/src/tx_trace_event_unfilter.o \
./src/threadx/src/tx_trace_initialize.o \
./src/threadx/src/tx_trace_interrupt_control.o \
./src/threadx/src/tx_trace_isr_enter_insert.o \
./src/threadx/src/tx_trace_isr_exit_insert.o \
./src/threadx/src/tx_trace_object_register.o \
./src/threadx/src/tx_trace_object_unregister.o \
./src/threadx/src/tx_trace_user_event_insert.o \
./src/threadx/src/txe_block_allocate.o \
./src/threadx/src/txe_block_pool_create.o \
./src/threadx/src/txe_block_pool_delete.o \
./src/threadx/src/txe_block_pool_info_get.o \
./src/threadx/src/txe_block_pool_prioritize.o \
./src/threadx/src/txe_block_release.o \
./src/threadx/src/txe_byte_allocate.o \
./src/threadx/src/txe_byte_pool_create.o \
./src/threadx/src/txe_byte_pool_delete.o \
./src/threadx/src/txe_byte_pool_info_get.o \
./src/threadx/src/txe_byte_pool_prioritize.o \
./src/threadx/src/txe_byte_release.o \
./src/threadx/src/txe_event_flags_create.o \
./src/threadx/src/txe_event_flags_delete.o \
./src/threadx/src/txe_event_flags_get.o \
./src/threadx/src/txe_event_flags_info_get.o \
./src/threadx/src/txe_event_flags_set.o \
./src/threadx/src/txe_event_flags_set_notify.o \
./src/threadx/src/txe_mutex_create.o \
./src/threadx/src/txe_mutex_delete.o \
./src/threadx/src/txe_mutex_get.o \
./src/threadx/src/txe_mutex_info_get.o \
./src/threadx/src/txe_mutex_prioritize.o \
./src/threadx/src/txe_mutex_put.o \
./src/threadx/src/txe_queue_create.o \
./src/threadx/src/txe_queue_delete.o \
./src/threadx/src/txe_queue_flush.o \
./src/threadx/src/txe_queue_front_send.o \
./src/threadx/src/txe_queue_info_get.o \
./src/threadx/src/txe_queue_prioritize.o \
./src/threadx/src/txe_queue_receive.o \
./src/threadx/src/txe_queue_send.o \
./src/threadx/src/txe_queue_send_notify.o \
./src/threadx/src/txe_semaphore_ceiling_put.o \
./src/threadx/src/txe_semaphore_create.o \
./src/threadx/src/txe_semaphore_delete.o \
./src/threadx/src/txe_semaphore_get.o \
./src/threadx/src/txe_semaphore_info_get.o \
./src/threadx/src/txe_semaphore_prioritize.o \
./src/threadx/src/txe_semaphore_put.o \
./src/threadx/src/txe_semaphore_put_notify.o \
./src/threadx/src/txe_thread_create.o \
./src/threadx/src/txe_thread_delete.o \
./src/threadx/src/txe_thread_entry_exit_notify.o \
./src/threadx/src/txe_thread_info_get.o \
./src/threadx/src/txe_thread_preemption_change.o \
./src/threadx/src/txe_thread_priority_change.o \
./src/threadx/src/txe_thread_relinquish.o \
./src/threadx/src/txe_thread_reset.o \
./src/threadx/src/txe_thread_resume.o \
./src/threadx/src/txe_thread_suspend.o \
./src/threadx/src/txe_thread_terminate.o \
./src/threadx/src/txe_thread_time_slice_change.o \
./src/threadx/src/txe_thread_wait_abort.o \
./src/threadx/src/txe_timer_activate.o \
./src/threadx/src/txe_timer_change.o \
./src/threadx/src/txe_timer_create.o \
./src/threadx/src/txe_timer_deactivate.o \
./src/threadx/src/txe_timer_delete.o \
./src/threadx/src/txe_timer_info_get.o 


# Each subdirectory must supply rules for building sources it contributes
src/threadx/src/%.o: ../src/threadx/src/%.c src/threadx/src/subdir.mk
	@echo 'Building file: $<'
	@echo 'Invoking: GNU Arm Cross C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -march=armv7e-m -mthumb -mlittle-endian -mfloat-abi=soft -munaligned-access -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -Wunused -Wuninitialized -Wall -Wextra -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -ggdb -DAT32F415RCT7 -DUSE_STDPERIPH_DRIVER -DTX_INCLUDE_USER_DEFINE_FILE -I"../src/cmsis" -I"../src/device" -I"../src/stdperiph/inc" -I"../src/threadx/inc" -I"../src/rtthread/include" -I"../src/bsp" -I"../src/components/rtt" -std=gnu11 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


